### ISSUE TITLE
loading page

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/ImageSelect#3]
Hi

While the adc loads, I can see all the images in full size for 1 second after it resizes to the correct size.
I can see the same issue across imageSelect, statements and statementList especially - for all of these there is at least 1 second where the adc looks full page size, until it loads to the right size.
If the internet connection is slower, or there are a lot of answers then it will take more than 1 second and is very noticable.

Could it be changed so that the responses are not shown, until all the properties and sizes are set correctly?

I'm attaching my test qex where you can see this across many types of adcs.
[Adcs_Example.zip](https://github.com/AskiaADX/ImageSelect/files/1394227/Adcs_Example.zip)

Regards
Diana

**Comment by Djedj** [comment]
Hi @diana1357 

It should be fixed in v2.0.5 of the ImageSelect adc

Let us know if it makes the trick ? And also on which other adc do you need this ? if you can sort this list by priority for you ?

Best Regards

**Comment by diana1357** [comment]
Thanks @Djedj - I did test and looks ok now.

Regarding the other adcs, I guess it would be  this order:
1. Statement
2. StatementOther
3. StatementList
4. Ranking
5. RankingOther

Please also note that for the quesitons with "other" options, you can see the open end text box of the "Other" option for 1 second on the page too. (before the question fully loads)

I've also looked at drag and drop, but this one seems to be ok, please let me know if not.

**Comment by Djedj** [comment]
Hi @diana1357 ,

Statement v2.0.5
StatementOther v2.0.5
StatementList v2.0.9

are done. Will look the Rankings adcs and let you know asap

Best Regards

**Comment by Djedj** [comment]
Hi @diana1357 

RankingIsotope v2.0.3
RankingIsotopeOther v2.0.2

Best Regards

**Comment by diana1357** [comment]
Hi @Djedj 

Thanks for the quick fix, I've tested all of them and they look good!
